//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hostelEntities : DbContext
    {
        public hostelEntities()
            : base("name=hostelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<courses> courses { get; set; }
        public DbSet<imagecrud> imagecrud { get; set; }
        public DbSet<registration> registration { get; set; }
        public DbSet<rooms> rooms { get; set; }
        public DbSet<states> states { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
