//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hostelEntities : DbContext
    {
        public hostelEntities()
            : base("name=hostelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<courses> courses { get; set; }
        public DbSet<imagecrud> imagecrud { get; set; }
        public DbSet<registration> registration { get; set; }
        public DbSet<rooms> rooms { get; set; }
        public DbSet<states> states { get; set; }
        public DbSet<adminlog> adminlog { get; set; }
    }
}
