//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public int roomno { get; set; }
        public int seater { get; set; }
        public int feespm { get; set; }
        public int foodstatus { get; set; }
        public System.DateTime stayfrom { get; set; }
        public int duration { get; set; }
        public string course { get; set; }
        public int regno { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }
        public long contactno { get; set; }
        public string emailid { get; set; }
        public long egycontactno { get; set; }
        public string guardianName { get; set; }
        public string guardianRelation { get; set; }
        public long guardianContactno { get; set; }
        public string corresAddress { get; set; }
        public string corresCIty { get; set; }
        public string corresState { get; set; }
        public int corresPincode { get; set; }
        public string pmntAddress { get; set; }
        public string pmntCity { get; set; }
        public string pmnatetState { get; set; }
        public int pmntPincode { get; set; }
        public System.DateTime postingDate { get; set; }
        public string updationDate { get; set; }
    }
}
