//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        public int id { get; set; }
        public int seater { get; set; }
        public int room_no { get; set; }
        public int fees { get; set; }
        public System.DateTime posting_date { get; set; }
    }
}
