//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        public int id { get; set; }
        public int seater { get; set; }
        public int room_no { get; set; }
        public int fees { get; set; }
        public System.DateTime posting_date { get; set; }
    }
}
