//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DataAccess.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class states
    {
        public int id { get; set; }
        public string State { get; set; }
    }
}
